name: hackathon_front
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  logger: ^1.3.0
  url_launcher: ^6.1.11
  flutter_easyloading: ^3.0.5
  emoji_picker_flutter: ^1.5.4
  flutter_screenutil: ^5.8.1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_markdown: ^0.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/basic_tags/